# Generated by Django 2.2.5 on 2019-09-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('id_number', models.BigIntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('date_employed', models.DateField()),
                ('profession', models.CharField(max_length=50)),
                ('subject_taught', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, upload_to='profile_pictures')),
            ],
        ),
    ]
