# Generated by Django 2.2.5 on 2019-09-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('registration_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=70)),
                ('phone_number', models.CharField(max_length=20)),
                ('date_joined', models.DateField()),
                ('image', models.ImageField(blank=True, upload_to='profile_pictures')),
                ('courses', models.ManyToManyField(to='course.Course')),
            ],
        ),
    ]
